### ISSUE TITLE
I come across the same problem closed before : it stopped at Search for ip address ，here is some more information

### ISSUE THREAD

**Issue by muguang** [craigz28/firmwalker#11]
I  test the ip search script in the following files:

➜  squashfs-root ls
bin  etc   include  libexec  mnt   sbin  tmp  var
dev  home  lib      linuxrc  proc  sys   usr  www

what different with other samples is that:   in **dev**  dictionary，there are some  device file listed：
some of them
console    sda10  sdc11  sde12  sdg13  sdi14  sdk15  sdm2   sdo3
fuse       sda11  sdc12  sde13  sdg14  sdi15  sdk2   sdm3   sdo4
log        sda12  sdc13  sde14  sdg15  sdi2   sdk3   sdm4   sdo5
md0        sda13  sdc14  sde15  sdg2   sdi3   sdk4   sdm5   sdo6
md1        sda14  sdc15  sde2   sdg3   sdi4   sdk5   sdm6   sdo7

when grep  command face  these device files， it will  stop.  so the firmware.sh will
 stop at this action.

just like this：
![screen shot 2017-08-24 at 15 38 20](https://user-images.githubusercontent.com/7148519/29655077-495e3dee-88e2-11e7-8e80-e68446c97042.png)

![screen shot 2017-08-24 at 15 44 08](https://user-images.githubusercontent.com/7148519/29655271-1a6569f8-88e3-11e7-8342-f3752d95209a.png)

I uploaded the dev file，and you can try it. 
[dev.tar.gz](https://github.com/craigz28/firmwalker/files/1248059/dev.tar.gz)

**Comment by craigz28** [comment]
Hi, I haven't been able to re-create this. Tested against several extracted file systems without issue.

**Comment by muguang** [comment]
the above test is in kali linux  ，and i try it in ubuntu and come across it again， here is the firmware download link [http://support.dlink.com/ProductInfo.aspx?m=DIR-850L](http://support.dlink.com/ProductInfo.aspx?m=DIR-850L).

In my opinion, if the there be some  devices files in  dev dictionary,  the grep command will failed .
I don‘t known whether   your tested  file systems 's  dev dictionary exist some device files.

Thank you.

**Comment by muguang** [comment]
may be this command is better   wget ftp://ftp2.dlink.com/PRODUCTS/DIR-850L/REVA/DIR-850L_REVA_FIRMWARE_1.12.B05_WW.ZIP

**Comment by craigz28** [comment]
Hey, just extracted the firmware from the dlink link you provided and ran firmwalker against without issue. Tried it on a Ubuntu 14.04 and 16.04, no issues on either. I've had issues with it stopping in the past due to file permissions in the extracted file system folder. Like it needed to be run using sudo.

**Comment by muguang** [comment]
I tried ubuntu 16.04 with the same firmware by using sudo ,failed again.
All in all， it's not matter much.  
graduate to you
