### ISSUE TITLE
Search stops at IP adress

### ISSUE THREAD

**Issue by Krish2402** [craigz28/firmwalker#12]
Search always stops at **Search for ip addresses** and not returning the ip addresses, tried with different firmware's  but same issue.

**Comment by j-marz** [comment]
I have also encountered this issue.

**Comment by j-marz** [comment]
I have created a PR which fixes this issue.
https://github.com/craigz28/firmwalker/pull/13

**Comment by craigz28** [comment]
Thanks to j-marz for the fixes.
